<?php
namespace Zodream\Infrastructure\ObjectExpand\Xml;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:47.
 */
class ArrayToXmlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayToXml
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayToXml;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Xml\ArrayToXml::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Xml\ArrayToXml::createXML
     * @todo   Implement testCreateXML().
     */
    public function testCreateXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
