<?php
namespace Zodream\Module\Gzo\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:52.
 */
class TemplateControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TemplateController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TemplateController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::confAction
     * @todo   Implement testConfAction().
     */
    public function testConfAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::modelAction
     * @todo   Implement testModelAction().
     */
    public function testModelAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::controllerAction
     * @todo   Implement testControllerAction().
     */
    public function testControllerAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::moduleAction
     * @todo   Implement testModuleAction().
     */
    public function testModuleAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Service\TemplateController::makeConfig
     * @todo   Implement testMakeConfig().
     */
    public function testMakeConfig()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
