<?php
namespace Zodream\Infrastructure\Session;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:49.
 */
class CacheSessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CacheSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CacheSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Session\CacheSession::useCustomStorage
     * @todo   Implement testUseCustomStorage().
     */
    public function testUseCustomStorage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\CacheSession::readSession
     * @todo   Implement testReadSession().
     */
    public function testReadSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\CacheSession::writeSession
     * @todo   Implement testWriteSession().
     */
    public function testWriteSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\CacheSession::destroySession
     * @todo   Implement testDestroySession().
     */
    public function testDestroySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\CacheSession::getTimeout
     * @todo   Implement testGetTimeout().
     */
    public function testGetTimeout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
