<?php
namespace Zodream\Infrastructure\Session;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:49.
 */
class DatabaseSessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DatabaseSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DatabaseSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::useCustomStorage
     * @todo   Implement testUseCustomStorage().
     */
    public function testUseCustomStorage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::regenerateID
     * @todo   Implement testRegenerateID().
     */
    public function testRegenerateID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::readSession
     * @todo   Implement testReadSession().
     */
    public function testReadSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::writeSession
     * @todo   Implement testWriteSession().
     */
    public function testWriteSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::destroySession
     * @todo   Implement testDestroySession().
     */
    public function testDestroySession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Session\DatabaseSession::gcSession
     * @todo   Implement testGcSession().
     */
    public function testGcSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
