<?php
namespace Zodream\Infrastructure\Support;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:50.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Template;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Support\Template::setDirectory
     * @todo   Implement testSetDirectory().
     */
    public function testSetDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Support\Template::setTag
     * @todo   Implement testSetTag().
     */
    public function testSetTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Support\Template::getText
     * @todo   Implement testGetText().
     */
    public function testGetText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Support\Template::replaceByArray
     * @todo   Implement testReplaceByArray().
     */
    public function testReplaceByArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Support\Template::replace
     * @todo   Implement testReplace().
     */
    public function testReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
