<?php
namespace Zodream\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:19.
 */
class AutoloadTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Autoload
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Autoload;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Autoload::registerAlias
     * @todo   Implement testRegisterAlias().
     */
    public function testRegisterAlias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Autoload::bindError
     * @todo   Implement testBindError().
     */
    public function testBindError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Autoload::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
