<?php
namespace Zodream\Domain\Rss;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:27.
 */
class BaseRssTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseRss
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseRss;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::setLink
     * @todo   Implement testSetLink().
     */
    public function testSetLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::setPubDate
     * @todo   Implement testSetPubDate().
     */
    public function testSetPubDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::getPubDate
     * @todo   Implement testGetPubDate().
     */
    public function testGetPubDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\BaseRss::addTag
     * @todo   Implement testAddTag().
     */
    public function testAddTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
