<?php
namespace Zodream\Domain\Rss;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:27.
 */
class RssItemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RssItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RssItem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Rss\RssItem::setGiud
     * @todo   Implement testSetGiud().
     */
    public function testSetGiud()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\RssItem::toString
     * @todo   Implement testToString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Rss\RssItem::enclosure
     * @todo   Implement testEnclosure().
     */
    public function testEnclosure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
