<?php
namespace Zodream\Domain\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:26.
 */
class AiModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AiModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AiModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Model\AiModel::tableName
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Model\AiModel::table
     * @todo   Implement testTable().
     */
    public function testTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Model\AiModel::getTableField
     * @todo   Implement testGetTableField().
     */
    public function testGetTableField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
