<?php
namespace Zodream\Domain\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:26.
 */
class ModelNotFoundExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ModelNotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModelNotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
