<?php
namespace Zodream\Infrastructure\ObjectExpand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:46.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Enum
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Enum;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Enum::isValidName
     * @todo   Implement testIsValidName().
     */
    public function testIsValidName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Enum::isValidValue
     * @todo   Implement testIsValidValue().
     */
    public function testIsValidValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
