<?php
namespace Zodream\Infrastructure\ObjectExpand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:46.
 */
class HtmlExpandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HtmlExpand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HtmlExpand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\HtmlExpand::compress
     * @todo   Implement testCompress().
     */
    public function testCompress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\HtmlExpand::filterHtml
     * @todo   Implement testFilterHtml().
     */
    public function testFilterHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\HtmlExpand::shortString
     * @todo   Implement testShortString().
     */
    public function testShortString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\HtmlExpand::formatUrl
     * @todo   Implement testFormatUrl().
     */
    public function testFormatUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
