<?php
namespace Zodream\Infrastructure\ObjectExpand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:47.
 */
class TreeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tree;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Tree::get_tree_child
     * @todo   Implement testGet_tree_child().
     */
    public function testGet_tree_child()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Tree::get_tree_parent
     * @todo   Implement testGet_tree_parent().
     */
    public function testGet_tree_parent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Tree::get_tree_ul
     * @todo   Implement testGet_tree_ul().
     */
    public function testGet_tree_ul()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Tree::get_tree_option
     * @todo   Implement testGet_tree_option().
     */
    public function testGet_tree_option()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\ObjectExpand\Tree::getTree
     * @todo   Implement testGetTree().
     */
    public function testGetTree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
