<?php
namespace Zodream\Domain\Html\Bootstrap;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:23.
 */
class FormWidgetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FormWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::begin
     * @todo   Implement testBegin().
     */
    public function testBegin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::csrf
     * @todo   Implement testCsrf().
     */
    public function testCsrf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::html
     * @todo   Implement testHtml().
     */
    public function testHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::hidden
     * @todo   Implement testHidden().
     */
    public function testHidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::text
     * @todo   Implement testText().
     */
    public function testText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::input
     * @todo   Implement testInput().
     */
    public function testInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::textArea
     * @todo   Implement testTextArea().
     */
    public function testTextArea()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::email
     * @todo   Implement testEmail().
     */
    public function testEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::number
     * @todo   Implement testNumber().
     */
    public function testNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::password
     * @todo   Implement testPassword().
     */
    public function testPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::checkbox
     * @todo   Implement testCheckbox().
     */
    public function testCheckbox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::radio
     * @todo   Implement testRadio().
     */
    public function testRadio()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::listBox
     * @todo   Implement testListBox().
     */
    public function testListBox()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::button
     * @todo   Implement testButton().
     */
    public function testButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::end
     * @todo   Implement testEnd().
     */
    public function testEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\FormWidget::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
