<?php
namespace Zodream\Domain\Html\Bootstrap;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:23.
 */
class HtmlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Html
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Html;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\Html::container
     * @todo   Implement testContainer().
     */
    public function testContainer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\Html::row
     * @todo   Implement testRow().
     */
    public function testRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\Html::col
     * @todo   Implement testCol().
     */
    public function testCol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
