<?php
namespace Zodream\Domain\Html\Bootstrap;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:23.
 */
class ModalWidgetTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ModalWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModalWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\ModalWidget::addEvent
     * @todo   Implement testAddEvent().
     */
    public function testAddEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Bootstrap\ModalWidget::addClose
     * @todo   Implement testAddClose().
     */
    public function testAddClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
