<?php
namespace Zodream\Infrastructure\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:43.
 */
class HttpResponseExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HttpResponseException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpResponseException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Http\HttpResponseException::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
