<?php
namespace Zodream\Module\Gzo\Domain\Database;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:50.
 */
class ColumnTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Column
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Column;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::type
     * @todo   Implement testType().
     */
    public function testType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::length
     * @todo   Implement testLength().
     */
    public function testLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::maxLength
     * @todo   Implement testMaxLength().
     */
    public function testMaxLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::getDefault
     * @todo   Implement testGetDefault().
     */
    public function testGetDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::isPK
     * @todo   Implement testIsPK().
     */
    public function testIsPK()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::canNull
     * @todo   Implement testCanNull().
     */
    public function testCanNull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::isAuto
     * @todo   Implement testIsAuto().
     */
    public function testIsAuto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\Gzo\Domain\Database\Column::getComment
     * @todo   Implement testGetComment().
     */
    public function testGetComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
