<?php
namespace Zodream\Infrastructure\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:36.
 */
class ConfigObjectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigObject;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Base\ConfigObject::setConfigs
     * @todo   Implement testSetConfigs().
     */
    public function testSetConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Base\ConfigObject::loadConfigs
     * @todo   Implement testLoadConfigs().
     */
    public function testLoadConfigs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
