<?php
namespace Zodream\Domain\Upload;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:35.
 */
class UploadInputTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UploadInput
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UploadInput;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Upload\UploadInput::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
