<?php
namespace Zodream\Infrastructure\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:45.
 */
class BaseMailerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseMailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseMailer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Mailer\BaseMailer::addReplyTo
     * @todo   Implement testAddReplyTo().
     */
    public function testAddReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Mailer\BaseMailer::addCC
     * @todo   Implement testAddCC().
     */
    public function testAddCC()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Mailer\BaseMailer::addBCC
     * @todo   Implement testAddBCC().
     */
    public function testAddBCC()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Mailer\BaseMailer::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
