<?php
namespace Zodream\Infrastructure\Pipeline;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:47.
 */
class FingersCrossedProcessorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FingersCrossedProcessor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FingersCrossedProcessor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Pipeline\FingersCrossedProcessor::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
