<?php
namespace Zodream\Domain\Git;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:22.
 */
class GitRepoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GitRepo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GitRepo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::createNew
     * @todo   Implement testCreateNew().
     */
    public function testCreateNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::setRepoPath
     * @todo   Implement testSetRepoPath().
     */
    public function testSetRepoPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::gitDirectoryPath
     * @todo   Implement testGitDirectoryPath().
     */
    public function testGitDirectoryPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::testGit
     * @todo   Implement testTestGit().
     */
    public function testTestGit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::run
     * @todo   Implement testRun().
     */
    public function testRun()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::status
     * @todo   Implement testStatus().
     */
    public function testStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::rm
     * @todo   Implement testRm().
     */
    public function testRm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::commit
     * @todo   Implement testCommit().
     */
    public function testCommit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::cloneTo
     * @todo   Implement testCloneTo().
     */
    public function testCloneTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::cloneFrom
     * @todo   Implement testCloneFrom().
     */
    public function testCloneFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::cloneRemote
     * @todo   Implement testCloneRemote().
     */
    public function testCloneRemote()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::clean
     * @todo   Implement testClean().
     */
    public function testClean()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::createBranch
     * @todo   Implement testCreateBranch().
     */
    public function testCreateBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::deleteBranch
     * @todo   Implement testDeleteBranch().
     */
    public function testDeleteBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::listBranches
     * @todo   Implement testListBranches().
     */
    public function testListBranches()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::listRemoteBranches
     * @todo   Implement testListRemoteBranches().
     */
    public function testListRemoteBranches()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::activeBranch
     * @todo   Implement testActiveBranch().
     */
    public function testActiveBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::checkout
     * @todo   Implement testCheckout().
     */
    public function testCheckout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::merge
     * @todo   Implement testMerge().
     */
    public function testMerge()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::fetch
     * @todo   Implement testFetch().
     */
    public function testFetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::addTag
     * @todo   Implement testAddTag().
     */
    public function testAddTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::listTags
     * @todo   Implement testListTags().
     */
    public function testListTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::push
     * @todo   Implement testPush().
     */
    public function testPush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::pull
     * @todo   Implement testPull().
     */
    public function testPull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Git\GitRepo::setEnv
     * @todo   Implement testSetEnv().
     */
    public function testSetEnv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
