<?php
namespace Zodream\Infrastructure\Database\Schema;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:40.
 */
class ColumnTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Column
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Column;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::setTable
     * @todo   Implement testSetTable().
     */
    public function testSetTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::setField
     * @todo   Implement testSetField().
     */
    public function testSetField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::setOldField
     * @todo   Implement testSetOldField().
     */
    public function testSetOldField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::setAfter
     * @todo   Implement testSetAfter().
     */
    public function testSetAfter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getAfter
     * @todo   Implement testGetAfter().
     */
    public function testGetAfter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getOldField
     * @todo   Implement testGetOldField().
     */
    public function testGetOldField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getField
     * @todo   Implement testGetField().
     */
    public function testGetField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::null
     * @todo   Implement testNull().
     */
    public function testNull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::notNull
     * @todo   Implement testNotNull().
     */
    public function testNotNull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::smallInt
     * @todo   Implement testSmallInt().
     */
    public function testSmallInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::bigInt
     * @todo   Implement testBigInt().
     */
    public function testBigInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::float
     * @todo   Implement testFloat().
     */
    public function testFloat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::double
     * @todo   Implement testDouble().
     */
    public function testDouble()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::decimal
     * @todo   Implement testDecimal().
     */
    public function testDecimal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::int
     * @todo   Implement testInt().
     */
    public function testInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::tinyint
     * @todo   Implement testTinyint().
     */
    public function testTinyint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::bool
     * @todo   Implement testBool().
     */
    public function testBool()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::signed
     * @todo   Implement testSigned().
     */
    public function testSigned()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::unsigned
     * @todo   Implement testUnsigned().
     */
    public function testUnsigned()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::char
     * @todo   Implement testChar().
     */
    public function testChar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::varchar
     * @todo   Implement testVarchar().
     */
    public function testVarchar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::text
     * @todo   Implement testText().
     */
    public function testText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::mediumtext
     * @todo   Implement testMediumtext().
     */
    public function testMediumtext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::longtext
     * @todo   Implement testLongtext().
     */
    public function testLongtext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::blob
     * @todo   Implement testBlob().
     */
    public function testBlob()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::mediumblob
     * @todo   Implement testMediumblob().
     */
    public function testMediumblob()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::longblob
     * @todo   Implement testLongblob().
     */
    public function testLongblob()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::dateTime
     * @todo   Implement testDateTime().
     */
    public function testDateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::date
     * @todo   Implement testDate().
     */
    public function testDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::time
     * @todo   Implement testTime().
     */
    public function testTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::timestamp
     * @todo   Implement testTimestamp().
     */
    public function testTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::year
     * @todo   Implement testYear().
     */
    public function testYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::enum
     * @todo   Implement testEnum().
     */
    public function testEnum()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::defaultVal
     * @todo   Implement testDefaultVal().
     */
    public function testDefaultVal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::comment
     * @todo   Implement testComment().
     */
    public function testComment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::ai
     * @todo   Implement testAi().
     */
    public function testAi()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::pk
     * @todo   Implement testPk().
     */
    public function testPk()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::fk
     * @todo   Implement testFk().
     */
    public function testFk()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::unique
     * @todo   Implement testUnique().
     */
    public function testUnique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::check
     * @todo   Implement testCheck().
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getSql
     * @todo   Implement testGetSql().
     */
    public function testGetSql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getAlterSql
     * @todo   Implement testGetAlterSql().
     */
    public function testGetAlterSql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Database\Schema\Column::getDropSql
     * @todo   Implement testGetDropSql().
     */
    public function testGetDropSql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
