<?php
namespace Zodream\Domain\View\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:35.
 */
class BladeCompilerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BladeCompiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BladeCompiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::compileString
     * @todo   Implement testCompileString().
     */
    public function testCompileString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::compileEchoDefaults
     * @todo   Implement testCompileEchoDefaults().
     */
    public function testCompileEchoDefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::getExtensions
     * @todo   Implement testGetExtensions().
     */
    public function testGetExtensions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::extend
     * @todo   Implement testExtend().
     */
    public function testExtend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::directive
     * @todo   Implement testDirective().
     */
    public function testDirective()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::getCustomDirectives
     * @todo   Implement testGetCustomDirectives().
     */
    public function testGetCustomDirectives()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::getRawTags
     * @todo   Implement testGetRawTags().
     */
    public function testGetRawTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::setRawTags
     * @todo   Implement testSetRawTags().
     */
    public function testSetRawTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::setContentTags
     * @todo   Implement testSetContentTags().
     */
    public function testSetContentTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::setEscapedContentTags
     * @todo   Implement testSetEscapedContentTags().
     */
    public function testSetEscapedContentTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::getContentTags
     * @todo   Implement testGetContentTags().
     */
    public function testGetContentTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::getEscapedContentTags
     * @todo   Implement testGetEscapedContentTags().
     */
    public function testGetEscapedContentTags()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\BladeCompiler::setEchoFormat
     * @todo   Implement testSetEchoFormat().
     */
    public function testSetEchoFormat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
