<?php
namespace Zodream\Domain\View\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:35.
 */
class DreamCompilerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DreamCompiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DreamCompiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\View\Engine\DreamCompiler::compileString
     * @todo   Implement testCompileString().
     */
    public function testCompileString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
