<?php
namespace Zodream\Domain\View\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:36.
 */
class TwigEngineTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TwigEngine
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TwigEngine;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\View\Engine\TwigEngine::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\View\Engine\TwigEngine::compile
     * @todo   Implement testCompile().
     */
    public function testCompile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
