<?php
namespace Zodream\Domain\Spider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:27.
 */
class HtmlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Html
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Html;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Spider\Html::getDocument
     * @todo   Implement testGetDocument().
     */
    public function testGetDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Spider\Html::getXPath
     * @todo   Implement testGetXPath().
     */
    public function testGetXPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Spider\Html::getNode
     * @todo   Implement testGetNode().
     */
    public function testGetNode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Spider\Html::getLinks
     * @todo   Implement testGetLinks().
     */
    public function testGetLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Spider\Html::expandLinks
     * @todo   Implement testExpandLinks().
     */
    public function testExpandLinks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
