<?php
namespace Zodream\Module\OAuth\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:54.
 */
class AuthorizeControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AuthorizeController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AuthorizeController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\OAuth\Service\AuthorizeController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Service\AuthorizeController::loginAction
     * @todo   Implement testLoginAction().
     */
    public function testLoginAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Service\AuthorizeController::authorizeAction
     * @todo   Implement testAuthorizeAction().
     */
    public function testAuthorizeAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
