<?php
namespace Zodream\Module\OAuth\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:54.
 */
class ClientControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ClientController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ClientController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\OAuth\Service\ClientController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
