<?php
namespace Zodream\Domain\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:20.
 */
class DataFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::clearError
     * @todo   Implement testClearError().
     */
    public function testClearError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::getError
     * @todo   Implement testGetError().
     */
    public function testGetError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::getFirstError
     * @todo   Implement testGetFirstError().
     */
    public function testGetFirstError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::filter
     * @todo   Implement testFilter().
     */
    public function testFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::filterOne
     * @todo   Implement testFilterOne().
     */
    public function testFilterOne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::validateOne
     * @todo   Implement testValidateOne().
     */
    public function testValidateOne()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::createFilter
     * @todo   Implement testCreateFilter().
     */
    public function testCreateFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\DataFilter::getFilters
     * @todo   Implement testGetFilters().
     */
    public function testGetFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
