<?php
namespace Zodream\Infrastructure\Error;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:41.
 */
class ErrorExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Error\ErrorException::isFatalError
     * @todo   Implement testIsFatalError().
     */
    public function testIsFatalError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Error\ErrorException::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
