<?php
namespace Zodream\Infrastructure\Error;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:41.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Error;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Error\Error::bootstrap
     * @todo   Implement testBootstrap().
     */
    public function testBootstrap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Error\Error::handleError
     * @todo   Implement testHandleError().
     */
    public function testHandleError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Error\Error::handleException
     * @todo   Implement testHandleException().
     */
    public function testHandleException()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Error\Error::handleShutdown
     * @todo   Implement testHandleShutdown().
     */
    public function testHandleShutdown()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
