<?php
namespace Zodream\Infrastructure\Database\Migrations;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:39.
 */
class MigrationTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Migration
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Migration;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
