<?php
namespace Zodream\Domain\Filter\Filters;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:20.
 */
class ConfirmFilterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfirmFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfirmFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Filter\Filters\ConfirmFilter::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Filter\Filters\ConfirmFilter::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
