<?php
namespace Zodream\Infrastructure\Http\Component;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:42.
 */
class HeaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Header
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Header;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setCookie
     * @todo   Implement testSetCookie().
     */
    public function testSetCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::removeCookie
     * @todo   Implement testRemoveCookie().
     */
    public function testRemoveCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::getCookies
     * @todo   Implement testGetCookies().
     */
    public function testGetCookies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::clearCookie
     * @todo   Implement testClearCookie().
     */
    public function testClearCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::all
     * @todo   Implement testAll().
     */
    public function testAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::keys
     * @todo   Implement testKeys().
     */
    public function testKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::replace
     * @todo   Implement testReplace().
     */
    public function testReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::has
     * @todo   Implement testHas().
     */
    public function testHas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setRedirect
     * @todo   Implement testSetRedirect().
     */
    public function testSetRedirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setXPoweredBy
     * @todo   Implement testSetXPoweredBy().
     */
    public function testSetXPoweredBy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setServer
     * @todo   Implement testSetServer().
     */
    public function testSetServer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentLanguage
     * @todo   Implement testSetContentLanguage().
     */
    public function testSetContentLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentMD5
     * @todo   Implement testSetContentMD5().
     */
    public function testSetContentMD5()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setCacheControl
     * @todo   Implement testSetCacheControl().
     */
    public function testSetCacheControl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setPragma
     * @todo   Implement testSetPragma().
     */
    public function testSetPragma()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setRetryAfter
     * @todo   Implement testSetRetryAfter().
     */
    public function testSetRetryAfter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setExpires
     * @todo   Implement testSetExpires().
     */
    public function testSetExpires()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setLastModified
     * @todo   Implement testSetLastModified().
     */
    public function testSetLastModified()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentLength
     * @todo   Implement testSetContentLength().
     */
    public function testSetContentLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentRange
     * @todo   Implement testSetContentRange().
     */
    public function testSetContentRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setAcceptRanges
     * @todo   Implement testSetAcceptRanges().
     */
    public function testSetAcceptRanges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentDisposition
     * @todo   Implement testSetContentDisposition().
     */
    public function testSetContentDisposition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setWWWAuthenticate
     * @todo   Implement testSetWWWAuthenticate().
     */
    public function testSetWWWAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setTransferEncoding
     * @todo   Implement testSetTransferEncoding().
     */
    public function testSetTransferEncoding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::setContentType
     * @todo   Implement testSetContentType().
     */
    public function testSetContentType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::getIterator
     * @todo   Implement testGetIterator().
     */
    public function testGetIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::parse
     * @todo   Implement testParse().
     */
    public function testParse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Component\Header::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
