<?php
namespace Zodream\Domain\Access\SSO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:18.
 */
class ServerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Server
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Server;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Access\SSO\Server::startBrokerSession
     * @todo   Implement testStartBrokerSession().
     */
    public function testStartBrokerSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Access\SSO\Server::attach
     * @todo   Implement testAttach().
     */
    public function testAttach()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Access\SSO\Server::login
     * @todo   Implement testLogin().
     */
    public function testLogin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Access\SSO\Server::logout
     * @todo   Implement testLogout().
     */
    public function testLogout()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Access\SSO\Server::userInfo
     * @todo   Implement testUserInfo().
     */
    public function testUserInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
