<?php
namespace Zodream\Infrastructure\Security;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:48.
 */
class AuthCodeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AuthCode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AuthCode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::setKey
     * @todo   Implement testSetKey().
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::setExpiry
     * @todo   Implement testSetExpiry().
     */
    public function testSetExpiry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::geExpiry
     * @todo   Implement testGeExpiry().
     */
    public function testGeExpiry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::encrypt
     * @todo   Implement testEncrypt().
     */
    public function testEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\AuthCode::decrypt
     * @todo   Implement testDecrypt().
     */
    public function testDecrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
