<?php
namespace Zodream\Infrastructure\Security;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:49.
 */
class HashTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Hash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Hash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Security\Hash::make
     * @todo   Implement testMake().
     */
    public function testMake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Hash::verify
     * @todo   Implement testVerify().
     */
    public function testVerify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Hash::needsRehash
     * @todo   Implement testNeedsRehash().
     */
    public function testNeedsRehash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Hash::setRounds
     * @todo   Implement testSetRounds().
     */
    public function testSetRounds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
