<?php
namespace Zodream\Infrastructure\Security;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:49.
 */
class RsaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Rsa
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Rsa;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::setPublicKey
     * @todo   Implement testSetPublicKey().
     */
    public function testSetPublicKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::setPrivateKey
     * @todo   Implement testSetPrivateKey().
     */
    public function testSetPrivateKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::getPublicKey
     * @todo   Implement testGetPublicKey().
     */
    public function testGetPublicKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::getPrivateKey
     * @todo   Implement testGetPrivateKey().
     */
    public function testGetPrivateKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::privateKeyEncrypt
     * @todo   Implement testPrivateKeyEncrypt().
     */
    public function testPrivateKeyEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::publicKeyEncrypt
     * @todo   Implement testPublicKeyEncrypt().
     */
    public function testPublicKeyEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::decryptPrivateEncrypt
     * @todo   Implement testDecryptPrivateEncrypt().
     */
    public function testDecryptPrivateEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::decryptPublicEncrypt
     * @todo   Implement testDecryptPublicEncrypt().
     */
    public function testDecryptPublicEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::encrypt
     * @todo   Implement testEncrypt().
     */
    public function testEncrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Security\Rsa::decrypt
     * @todo   Implement testDecrypt().
     */
    public function testDecrypt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
