<?php
namespace Zodream\Service\Rest\OAuth\Grant;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:53.
 */
class BaseGrantTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseGrant
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseGrant;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
