<?php
namespace Zodream\Service\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:56.
 */
class BaseControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Service\Controller\BaseController::runMethod
     * @todo   Implement testRunMethod().
     */
    public function testRunMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\BaseController::forward
     * @todo   Implement testForward().
     */
    public function testForward()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\BaseController::hasMethod
     * @todo   Implement testHasMethod().
     */
    public function testHasMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
