<?php
namespace Zodream\Service\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:56.
 */
class ModuleControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ModuleController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ModuleController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Service\Controller\ModuleController::configAction
     * @todo   Implement testConfigAction().
     */
    public function testConfigAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\ModuleController::jsonSuccess
     * @todo   Implement testJsonSuccess().
     */
    public function testJsonSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\ModuleController::jsonFailure
     * @todo   Implement testJsonFailure().
     */
    public function testJsonFailure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\ModuleController::hasMethod
     * @todo   Implement testHasMethod().
     */
    public function testHasMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
