<?php
namespace Zodream\Service\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:56.
 */
class ModuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Module
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Module;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Service\Controller\Module::getBasePath
     * @todo   Implement testGetBasePath().
     */
    public function testGetBasePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\Module::getViewPath
     * @todo   Implement testGetViewPath().
     */
    public function testGetViewPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\Module::getControllerNamespace
     * @todo   Implement testGetControllerNamespace().
     */
    public function testGetControllerNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
