<?php
namespace Zodream\Service\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:56.
 */
class RestControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RestController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RestController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Service\Controller\RestController::ajaxSuccess
     * @todo   Implement testAjaxSuccess().
     */
    public function testAjaxSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Service\Controller\RestController::ajaxFailure
     * @todo   Implement testAjaxFailure().
     */
    public function testAjaxFailure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
