<?php
namespace Zodream\Domain\Debug;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:19.
 */
class MemoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Memory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Memory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Debug\Memory::CPU
     * @todo   Implement testCPU().
     */
    public function testCPU()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Debug\Memory::usage
     * @todo   Implement testUsage().
     */
    public function testUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Debug\Memory::peakUsage
     * @todo   Implement testPeakUsage().
     */
    public function testPeakUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
