<?php
namespace Zodream\Domain\Html;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:25.
 */
class TreeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tree
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tree;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Domain\Html\Tree::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Tree::makeTree
     * @todo   Implement testMakeTree().
     */
    public function testMakeTree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Tree::makeIdTree
     * @todo   Implement testMakeIdTree().
     */
    public function testMakeIdTree()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Tree::makeTreeForHtml
     * @todo   Implement testMakeTreeForHtml().
     */
    public function testMakeTreeForHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Domain\Html\Tree::toJson
     * @todo   Implement testToJson().
     */
    public function testToJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
