<?php
namespace Zodream\Infrastructure\I18n;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:45.
 */
class PhpSourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PhpSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PhpSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\I18n\PhpSource::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\I18n\PhpSource::reset
     * @todo   Implement testReset().
     */
    public function testReset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
