<?php
namespace Zodream\Infrastructure\Caching;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:37.
 */
class DatabaseCacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DatabaseCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DatabaseCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Caching\DatabaseCache::command
     * @todo   Implement testCommand().
     */
    public function testCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Caching\DatabaseCache::gc
     * @todo   Implement testGc().
     */
    public function testGc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
