<?php
namespace Zodream\Infrastructure\Caching;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:37.
 */
class FileCacheTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileCache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileCache;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Caching\FileCache::setDirectory
     * @todo   Implement testSetDirectory().
     */
    public function testSetDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Caching\FileCache::getCacheFile
     * @todo   Implement testGetCacheFile().
     */
    public function testGetCacheFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Caching\FileCache::gc
     * @todo   Implement testGc().
     */
    public function testGc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
