<?php
namespace Zodream\Module\OAuth\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:52.
 */
class BaseModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BaseModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BaseModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\BaseModel::getTable
     * @todo   Implement testGetTable().
     */
    public function testGetTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\BaseModel::dropTable
     * @todo   Implement testDropTable().
     */
    public function testDropTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\BaseModel::generateAccessToken
     * @todo   Implement testGenerateAccessToken().
     */
    public function testGenerateAccessToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\BaseModel::isExpire
     * @todo   Implement testIsExpire().
     */
    public function testIsExpire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
