<?php
namespace Zodream\Module\OAuth\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:53.
 */
class OAuthClientModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var OAuthClientModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OAuthClientModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\OAuthClientModel::tableName
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Module\OAuth\Domain\OAuthClientModel::createTable
     * @todo   Implement testCreateTable().
     */
    public function testCreateTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
