<?php
namespace Zodream\Infrastructure\Http\Input;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-04 at 15:40:44.
 */
class OtherTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Other
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Other;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getAuth
     * @todo   Implement testGetAuth().
     */
    public function testGetAuth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getMethod
     * @todo   Implement testGetMethod().
     */
    public function testGetMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getHost
     * @todo   Implement testGetHost().
     */
    public function testGetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getIp
     * @todo   Implement testGetIp().
     */
    public function testGetIp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getIsMobile
     * @todo   Implement testGetIsMobile().
     */
    public function testGetIsMobile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getOs
     * @todo   Implement testGetOs().
     */
    public function testGetOs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Zodream\Infrastructure\Http\Input\Other::getBrowser
     * @todo   Implement testGetBrowser().
     */
    public function testGetBrowser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
